"""Added autoincrement to id column

Revision ID: c1e76df6525d
Revises: 7c2e35362860
Create Date: 2024-08-23 19:07:40.930136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1e76df6525d'
down_revision: Union[str, None] = '7c2e35362860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_categories_id', table_name='categories')
    op.drop_index('ix_products_id', table_name='products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_products_id', 'products', ['id'], unique=False)
    op.create_index('ix_categories_id', 'categories', ['id'], unique=False)
    # ### end Alembic commands ###
